# Neural network from scratch
- Trong notebook này, tôi sẽ thử nghiệm mạng neurall fully-connected được tự cài đặt thông qua bài toán đó là bài toán XOR. 
- Tôi sẽ đánh giá hiệu của code thông qua việc cài đặt song song giữa pytorch và module do tôi cài đặt, so sánh hiệu quả giữa chúng.  

# XOR 


In [1]:
import numpy as np 

# prepare training data 
X_train = np.array([[[0,0]], [[0,1]], [[1,0]], [[1,1]]])
y_train = np.array([[[0]], [[1]], [[1]], [[0]]])


In [2]:
y_train[1].shape

(1, 1)

In [3]:
EPOCHS = 1000
LEARNING_RATE = 0.1


In [4]:
from deepmodel.nnets.network import Network
from deepmodel.nnets.layer import Linear
from deepmodel.nnets.activations import Tanh
from deepmodel.nnets.loss import MSELoss

# setup model 
model = Network()
model.add(Linear(2, 3))
model.add(Tanh())
model.add(Linear(3, 1))
model.add(Tanh())

# training 
loss = MSELoss()
model.setLoss(loss)
model.train(X_train, y_train, LEARNING_RATE, EPOCHS)

# predict 
model.predict(X_train)


Epoch 1: error = 0.322683
Epoch 2: error = 0.302714
Epoch 3: error = 0.290261
Epoch 4: error = 0.281946
Epoch 5: error = 0.276073
Epoch 6: error = 0.271725
Epoch 7: error = 0.268381
Epoch 8: error = 0.265724
Epoch 9: error = 0.263555
Epoch 10: error = 0.261742
Epoch 11: error = 0.260197
Epoch 12: error = 0.258857
Epoch 13: error = 0.257676
Epoch 14: error = 0.256620
Epoch 15: error = 0.255664
Epoch 16: error = 0.254789
Epoch 17: error = 0.253979
Epoch 18: error = 0.253223
Epoch 19: error = 0.252512
Epoch 20: error = 0.251836
Epoch 21: error = 0.251192
Epoch 22: error = 0.250573
Epoch 23: error = 0.249975
Epoch 24: error = 0.249397
Epoch 25: error = 0.248834
Epoch 26: error = 0.248284
Epoch 27: error = 0.247747
Epoch 28: error = 0.247220
Epoch 29: error = 0.246702
Epoch 30: error = 0.246192
Epoch 31: error = 0.245690
Epoch 32: error = 0.245193
Epoch 33: error = 0.244703
Epoch 34: error = 0.244218
Epoch 35: error = 0.243738
Epoch 36: error = 0.243262
Epoch 37: error = 0.242790
Epoch 38: 

array([[[ 0.03035604]],

       [[ 0.91686762]],

       [[ 0.94377751]],

       [[-0.09082836]]])

In [5]:
y_train 

array([[[0]],

       [[1]],

       [[1]],

       [[0]]])

In [6]:
import torch
from torch import nn
import torch.optim as optim

# Prepare data: convert NumPy arrays to PyTorch tensors
X_train = torch.tensor([[[0, 0]], [[0, 1]], [[1, 0]], [[1, 1]]], dtype=torch.float32)
y_train = torch.tensor([[[0]], [[1]], [[1]], [[0]]], dtype=torch.float32)

# Define the model
model = nn.Sequential(
    nn.Linear(2, 4), 
    nn.Tanh(), 
    nn.Linear(4, 1), 
    nn.Tanh()
)

# Define loss function and optimizer
loss_criter = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=LEARNING_RATE)


# Training loop
for epoch in range(EPOCHS): 
    model.train()  # Set model to training mode
    
    for j in range(len(X_train)): 
        optimizer.zero_grad()  # Clear gradients

        # Extract data points and reshape as needed
        x, y = X_train[j].view(-1, 2), y_train[j].view(-1, 1)  # Reshape for batch

        # Forward pass
        y_pred = model(x)

        # Compute loss
        loss = loss_criter(y_pred, y)

        # Backward pass
        loss.backward()

        # Update weights
        optimizer.step()

# After training, switch to evaluation mode
model.eval()

# Make predictions on the entire training set
with torch.no_grad():  # No need to track gradients during inference
    y_pred = model(X_train.view(-1, 2))  # Reshape X_train for batch prediction

print(y_pred)


tensor([[ 7.1391e-04],
        [ 9.7527e-01],
        [ 9.7891e-01],
        [-1.5815e-03]])
